# -*- coding: utf-8 -*-
"""Aula08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nrun0iIf3s3hXD4GVLqAiaPJxSZke12o
"""

#criador de frases 'motivacionais'
import random
lista1 = ['voce', 'vai', 'consequir', 'acreditamos']
lista2 = ['tenha', 'fé','lute', 'alcance',]
lista3 = ['sucesso', 'constantemente','seja', 'forte']
lista4 = ['execute','confiamos','sempre','melhor']
p1 = lista1[random.randint(0,3)]
p2 = lista2[random.randint(0,3)]
p3 = lista3[random.randint(0,3)]
p4 = lista4[random.randint(0,3)]
print(f'{p1} {p2} {p3} {p4}')

#gerador de nomes de 'loja'
lista1 = ['lan','house','internet']
lista2 = ['roupa','atacado','multimarcas']
lista3 = ['casa','sua','melhor','galpao']
while True:
    modelo = int(input('''escolha o modelo:
    modelo =  tecnologia digite 1
    modelo = roupas digite 2
    medelo = 3 para sair
    '''))
    if modelo == 1:
        l1 = lista1[random.randint(0,2)]
        l2 = lista2[random.randint(0,2)]
        print(f'{l1} das/dos {l2}')           
    elif modelo == 2:
        l1 = lista1[random.randint(0,2)]
        l2 = lista2[random.randint(0,2)]
        print(f'{l1} das/dos {l2}')
    elif modelo == 3:
        print('voce saiu do sistema') 
        break   
    else:
        print('modelo nao indentificado')